# Dockerfile.base

# 1. PyTorch CPU 기반 경량 이미지
FROM python:3.9-slim

# 2. 작업 디렉토리 생성
WORKDIR /app

# 3 시스템 패키지 설치 (git-lfs 포함)
RUN apt-get update && \
    apt-get install -y \
        ffmpeg \
        libgl1 \
        libglib2.0-0 \
        libsm6 \
        libxext6 \
        libxrender-dev \
        python3-opencv \
        streamlink \
        git \
        curl \
        git-lfs \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 4. Git LFS 초기화
RUN git lfs install

COPY requirements.txt .

# 5. PyTorch CPU 버전 설치
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip setuptools wheel && \
    pip install --no-cache-dir -r requirements.txt

# docker build -f Dockerfile.base -t sychol/careeyes-aiserver-base:latest .