# aiserver/docker-compose.yml

services:
  careeyes-ai:
    container_name: careeyes-ai-container
    build:
      context: .
      dockerfile: Dockerfile
    image: sychol/careeyes-aiserver:latest
    volumes:
      - /mnt/images:/app/images
    ports:
      - "5000:5000"
    restart: always

#    runtime: nvidia  # GPU 사용
